apiVersion: apps/v1
kind: Deployment
metadata:
  name: cfrs-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cfrs-frontend
  template:
    metadata:
      labels:
        app: cfrs-frontend
    spec:
      containers:
      - name: frontend
        image: rajb957/cfrs-frontend:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: cfrs-frontend
  labels:
    app: cfrs-frontend
spec:
  type: NodePort  # To expose frontend outside of cluster
  selector:
    app: cfrs-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001  # Custom NodePort for external access (range: 30000-32767)
