apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace:  default
data:
  elasticsearch.yml: |
    cluster.name: "elasticsearch-cluster"
    node.name: "${HOSTNAME}"
    network.host: 0.0.0.0
    discovery.seed_hosts: ["elasticsearch"]
    cluster.initial_master_nodes: ["elasticsearch"]
    xpack.security.enabled: true
    xpack.security.enrollment.enabled: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace:  default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
        ports:
        - containerPort: 9200
        - containerPort: 9300
        env:
        - name: discovery.type
          value: "single-node"
        volumeMounts:
        - name: elasticsearch-config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
      volumes:
      - name: elasticsearch-config
        configMap:
          name: elasticsearch-config
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: <your-namespace>
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
  - name: http
    protocol: TCP
    port: 9200
    targetPort: 9200
  - name: transport
    protocol: TCP
    port: 9300
    targetPort: 9300
