apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:8.10.0
        ports:
        - containerPort: 5044
          name: logstash
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/logstash/pipeline
    volumes:
    - name: config-volume
      configMap:
        name: logstash-config
