---
- hosts: database
  become: true
  become_method: sudo
  tasks:
    - name: Ensure PostgreSQL client is installed
      dnf:
        name: postgresql
        state: present

    - name: Restore database
      shell: |
        kubectl exec -i $(kubectl get pod -l app=postgres -o jsonpath='{.items[0].metadata.name}') -- psql -U postgres -d cfrs_db < /tmp/backup.sql
      args:
        executable: /bin/bash
